#!/bin/bash 

read fst
ARGS="$@"
if [ "$fst" == "make" ]; then
  pico2wave -w CREATED_AUDIOBOOK.wav "$ARGS"
else
  pico2wave -w tmp.wav "$ARGS"
  sox CREATED_AUDIOBOOK.wav tmp.wav out.wav
  mv out.wav CREATED_AUDIOBOOK.wav
fi
rm -f tmp.wav
